#!/bin/vbash

set firewall ipv6 forward filter default-action 'accept'
set firewall ipv6 forward filter rule 1 action 'accept'
set firewall ipv6 forward filter rule 1 state established 'enable'
set firewall ipv6 forward filter rule 2 action 'accept'
set firewall ipv6 forward filter rule 2 state related 'enable'
set firewall ipv6 forward filter rule 101 action 'accept'
set firewall ipv6 forward filter rule 101 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv6 forward filter rule 101 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv6 forward filter rule 106 action 'drop'
set firewall ipv6 forward filter rule 106 description 'ZONE_CONTAINERS_v6 default-action'
set firewall ipv6 forward filter rule 106 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv6 forward filter rule 121 action 'accept'
set firewall ipv6 forward filter rule 121 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv6 forward filter rule 121 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv6 forward filter rule 126 action 'drop'
set firewall ipv6 forward filter rule 126 description 'ZONE_IOT_v6 default-action'
set firewall ipv6 forward filter rule 126 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv6 forward filter rule 131 action 'accept'
set firewall ipv6 forward filter rule 131 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv6 forward filter rule 131 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv6 forward filter rule 136 action 'drop'
set firewall ipv6 forward filter rule 136 description 'ZONE_HOME_v6 default-action'
set firewall ipv6 forward filter rule 136 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv6 forward filter rule 141 action 'accept'
set firewall ipv6 forward filter rule 141 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv6 forward filter rule 141 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv6 forward filter rule 146 action 'drop'
set firewall ipv6 forward filter rule 146 description 'ZONE_INFRA_v6 default-action'
set firewall ipv6 forward filter rule 146 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv6 forward filter rule 151 action 'accept'
set firewall ipv6 forward filter rule 151 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv6 forward filter rule 151 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv6 forward filter rule 156 action 'drop'
set firewall ipv6 forward filter rule 156 description 'ZONE_MGMT_v6 default-action'
set firewall ipv6 forward filter rule 156 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv6 forward filter rule 161 action 'accept'
set firewall ipv6 forward filter rule 161 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv6 forward filter rule 161 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv6 forward filter rule 166 action 'drop'
set firewall ipv6 forward filter rule 166 description 'ZONE_CCTV_v6 default-action'
set firewall ipv6 forward filter rule 166 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv6 forward filter rule 171 action 'accept'
set firewall ipv6 forward filter rule 171 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv6 forward filter rule 171 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv6 forward filter rule 176 action 'drop'
set firewall ipv6 forward filter rule 176 description 'ZONE_WAN_v6 default-action'
set firewall ipv6 forward filter rule 176 outbound-interface interface-group 'ZONE_WAN'

set firewall ipv6 input filter default-action 'accept'
set firewall ipv6 input filter rule 1 action 'accept'
set firewall ipv6 input filter rule 1 state established 'enable'
set firewall ipv6 input filter rule 2 action 'accept'
set firewall ipv6 input filter rule 2 state related 'enable'
set firewall ipv6 input filter rule 101 action 'drop'

set firewall ipv6 output filter default-action 'accept'
set firewall ipv6 output filter rule 1 action 'accept'
set firewall ipv6 output filter rule 1 state established 'enable'
set firewall ipv6 output filter rule 2 action 'accept'
set firewall ipv6 output filter rule 2 state related 'enable'
set firewall ipv6 output filter rule 101 action 'drop'

# Ensure VyOS can talk to itself
set firewall ipv6 output filter rule 10 action accept
set firewall ipv6 output filter rule 10 source group address-group FW_AG_ROUTER_ADDR_IPV6
set firewall ipv6 output filter rule 10 destination group address-group FW_AG_ROUTER_ADDR_IPV6
set firewall ipv6 input  filter rule 10 action accept
set firewall ipv6 input  filter rule 10 source group address-group FW_AG_ROUTER_ADDR_IPV6
set firewall ipv6 input  filter rule 10 destination group address-group FW_AG_ROUTER_ADDR_IPV6