
############################################################################################################ 
# DEFAULT FILTER POLICY
############################################################################################################
# Default forward policy
set firewall ipv4 forward filter default-action 'accept'
set firewall ipv4 forward filter rule 1 action 'accept'
set firewall ipv4 forward filter rule 1 state established 'enable'
set firewall ipv4 forward filter rule 2 action 'drop'
set firewall ipv4 forward filter rule 2 state invalid 'enable'
set firewall ipv4 forward filter rule 3 action 'accept'
set firewall ipv4 forward filter rule 3 state related 'enable'
# Default input policy
set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 1 action 'accept'
set firewall ipv4 input filter rule 1 state established 'enable'
set firewall ipv4 input filter rule 2 action 'drop'
set firewall ipv4 input filter rule 2 state invalid 'enable'
set firewall ipv4 input filter rule 3 action 'accept'
set firewall ipv4 input filter rule 3 state related 'enable'
# Default output policy
set firewall ipv4 output filter default-action 'accept'
set firewall ipv4 output filter rule 1 action 'accept'
set firewall ipv4 output filter rule 1 state established 'enable'
set firewall ipv4 output filter rule 2 action 'drop'
set firewall ipv4 output filter rule 2 state invalid 'enable'
set firewall ipv4 output filter rule 3 action 'accept'
set firewall ipv4 output filter rule 3 state related 'enable'
# Ensure VyOS can talk to itself
set firewall ipv4 output filter rule 10 action accept
set firewall ipv4 output filter rule 10 source group address-group FW_AG_ROUTER_ADDR_IPV4
set firewall ipv4 output filter rule 10 destination group address-group FW_AG_ROUTER_ADDR_IPV4
set firewall ipv4 input  filter rule 10 action accept
set firewall ipv4 input  filter rule 10 source group address-group FW_AG_ROUTER_ADDR_IPV4
set firewall ipv4 input  filter rule 10 destination group address-group FW_AG_ROUTER_ADDR_IPV4

############################################################################################################ 
# FIREWALL FILTER
############################################################################################################
## Forward filter
# WAN
set firewall ipv4 forward filter rule 101 action 'accept'
set firewall ipv4 forward filter rule 101 description 'WAN intra-zone policies'
set firewall ipv4 forward filter rule 101 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 101 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 102 action 'jump'
set firewall ipv4 forward filter rule 102 description 'WAN to MGMT policies'
set firewall ipv4 forward filter rule 102 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 102 jump-target 'WAN-MGMT-v4'
set firewall ipv4 forward filter rule 102 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 103 action 'jump'
set firewall ipv4 forward filter rule 103 description 'WAN to INFRA policies'
set firewall ipv4 forward filter rule 103 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 103 jump-target 'WAN-INFRA-v4'
set firewall ipv4 forward filter rule 103 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 104 action 'jump'
set firewall ipv4 forward filter rule 104 description 'WAN to HOME policies'
set firewall ipv4 forward filter rule 104 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 104 jump-target 'WAN-HOME-v4'
set firewall ipv4 forward filter rule 104 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 105 action 'jump'
set firewall ipv4 forward filter rule 105 description 'WAN to IOT policies'
set firewall ipv4 forward filter rule 105 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 105 jump-target 'WAN-IOT-v4'
set firewall ipv4 forward filter rule 105 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 106 action 'jump'
set firewall ipv4 forward filter rule 106 description 'WAN to CCTV policies'
set firewall ipv4 forward filter rule 106 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 106 jump-target 'WAN-CCTV-v4'
set firewall ipv4 forward filter rule 106 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 107 action 'jump'
set firewall ipv4 forward filter rule 107 description 'WAN to CONTAINERS policies'
set firewall ipv4 forward filter rule 107 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 107 jump-target 'WAN-CONTAINERS-v4'
set firewall ipv4 forward filter rule 107 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 110 action 'drop'
set firewall ipv4 forward filter rule 110 description 'ZONE WAN default-action'
set firewall ipv4 forward filter rule 110 outbound-interface interface-group 'ZONE_WAN'
# MGMT
set firewall ipv4 forward filter rule 201 action 'accept'
set firewall ipv4 forward filter rule 201 description 'MGMT intra-zone policies'
set firewall ipv4 forward filter rule 201 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 201 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 202 action 'jump'
set firewall ipv4 forward filter rule 202 description 'MGMT to INFRA policies'
set firewall ipv4 forward filter rule 202 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 202 jump-target 'MGMT-INFRA-v4'
set firewall ipv4 forward filter rule 202 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 203 action 'jump'
set firewall ipv4 forward filter rule 203 description 'MGMT to HOME policies'
set firewall ipv4 forward filter rule 203 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 203 jump-target 'MGMT-HOME-v4'
set firewall ipv4 forward filter rule 203 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 204 action 'jump'
set firewall ipv4 forward filter rule 204 description 'MGMT to IOT policies'
set firewall ipv4 forward filter rule 204 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 204 jump-target 'MGMT-IOT-v4'
set firewall ipv4 forward filter rule 204 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 205 action 'jump'
set firewall ipv4 forward filter rule 205 description 'MGMT to CCTV policies'
set firewall ipv4 forward filter rule 205 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 205 jump-target 'MGMT-CCTV-v4'
set firewall ipv4 forward filter rule 205 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 206 action 'jump'
set firewall ipv4 forward filter rule 206 description 'MGMT to CONTAINERS policies'
set firewall ipv4 forward filter rule 206 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 206 jump-target 'MGMT-CONTAINERS-v4'
set firewall ipv4 forward filter rule 206 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 207 action 'jump'
set firewall ipv4 forward filter rule 207 description 'MGMT to WAN policies'
set firewall ipv4 forward filter rule 207 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 207 jump-target 'MGMT-WAN-v4'
set firewall ipv4 forward filter rule 207 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 210 action 'drop'
set firewall ipv4 forward filter rule 210 description 'ZONE MGMT default-action'
set firewall ipv4 forward filter rule 210 outbound-interface interface-group 'ZONE_MGMT'
# INFRA
set firewall ipv4 forward filter rule 301 action 'accept'
set firewall ipv4 forward filter rule 301 description 'INFRA intra-zone policies'
set firewall ipv4 forward filter rule 301 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 301 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 302 action 'jump'
set firewall ipv4 forward filter rule 302 description 'INFRA to MGMT policies'
set firewall ipv4 forward filter rule 302 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 302 jump-target 'INFRA-MGMT-v4'
set firewall ipv4 forward filter rule 302 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 303 action 'jump'
set firewall ipv4 forward filter rule 303 description 'INFRA to HOME policies'
set firewall ipv4 forward filter rule 303 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 303 jump-target 'INFRA-HOME-v4'
set firewall ipv4 forward filter rule 303 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 304 action 'jump'
set firewall ipv4 forward filter rule 304 description 'INFRA to IOT policies'
set firewall ipv4 forward filter rule 304 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 304 jump-target 'INFRA-IOT-v4'
set firewall ipv4 forward filter rule 304 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 305 action 'jump'
set firewall ipv4 forward filter rule 305 description 'INFRA to CCTV policies'
set firewall ipv4 forward filter rule 305 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 305 jump-target 'INFRA-CCTV-v4'
set firewall ipv4 forward filter rule 305 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 306 action 'jump'
set firewall ipv4 forward filter rule 306 description 'INFRA to CONTAINERS policies'
set firewall ipv4 forward filter rule 306 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 306 jump-target 'INFRA-CONTAINERS-v4'
set firewall ipv4 forward filter rule 306 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 307 action 'jump'
set firewall ipv4 forward filter rule 307 description 'INFRA to WAN policies'
set firewall ipv4 forward filter rule 307 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 307 jump-target 'INFRA-WAN-v4'
set firewall ipv4 forward filter rule 307 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 310 action 'drop'
set firewall ipv4 forward filter rule 310 description 'ZONE INFRA default-action'
set firewall ipv4 forward filter rule 310 outbound-interface interface-group 'ZONE_INFRA'
# HOME
set firewall ipv4 forward filter rule 401 action 'accept'
set firewall ipv4 forward filter rule 401 description 'HOME intra-zone policies'
set firewall ipv4 forward filter rule 401 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 401 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 402 action 'jump'
set firewall ipv4 forward filter rule 402 description 'HOME to MGMT policies'
set firewall ipv4 forward filter rule 402 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 402 jump-target 'HOME-MGMT-v4'
set firewall ipv4 forward filter rule 402 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 403 action 'jump'
set firewall ipv4 forward filter rule 403 description 'HOME to INFRA policies'
set firewall ipv4 forward filter rule 403 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 403 jump-target 'HOME-INFRA-v4'
set firewall ipv4 forward filter rule 403 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 404 action 'jump'
set firewall ipv4 forward filter rule 404 description 'HOME to IOT policies'
set firewall ipv4 forward filter rule 404 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 404 jump-target 'HOME-IOT-v4'
set firewall ipv4 forward filter rule 404 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 405 action 'jump'
set firewall ipv4 forward filter rule 405 description 'HOME to CCTV policies'
set firewall ipv4 forward filter rule 405 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 405 jump-target 'HOME-CCTV-v4'
set firewall ipv4 forward filter rule 405 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 406 action 'jump'
set firewall ipv4 forward filter rule 406 description 'HOME to CONTAINERS policies'
set firewall ipv4 forward filter rule 406 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 406 jump-target 'HOME-CONTAINERS-v4'
set firewall ipv4 forward filter rule 406 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 407 action 'jump'
set firewall ipv4 forward filter rule 407 description 'HOME to WAN policies'
set firewall ipv4 forward filter rule 407 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 407 jump-target 'HOME-WAN-v4'
set firewall ipv4 forward filter rule 407 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 410 action 'drop'
set firewall ipv4 forward filter rule 410 description 'ZONE HOME default-action'
set firewall ipv4 forward filter rule 410 outbound-interface interface-group 'ZONE_HOME'
# IOT
set firewall ipv4 forward filter rule 501 action 'accept'
set firewall ipv4 forward filter rule 501 description 'IOT intra-zone policies'
set firewall ipv4 forward filter rule 501 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 501 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 502 action 'jump'
set firewall ipv4 forward filter rule 502 description 'IOT to MGMT policies'
set firewall ipv4 forward filter rule 502 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 502 jump-target 'IOT-MGMT-v4'
set firewall ipv4 forward filter rule 502 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 503 action 'jump'
set firewall ipv4 forward filter rule 503 description 'IOT to INFRA policies'
set firewall ipv4 forward filter rule 503 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 503 jump-target 'IOT-INFRA-v4'
set firewall ipv4 forward filter rule 503 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 504 action 'jump'
set firewall ipv4 forward filter rule 504 description 'IOT to HOME policies'
set firewall ipv4 forward filter rule 504 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 504 jump-target 'IOT-HOME-v4'
set firewall ipv4 forward filter rule 504 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 505 action 'jump'
set firewall ipv4 forward filter rule 505 description 'IOT to CCTV policies'
set firewall ipv4 forward filter rule 505 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 505 jump-target 'IOT-CCTV-v4'
set firewall ipv4 forward filter rule 505 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 506 action 'jump'
set firewall ipv4 forward filter rule 506 description 'IOT to CONTAINERS policies'
set firewall ipv4 forward filter rule 506 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 506 jump-target 'IOT-CONTAINERS-v4'
set firewall ipv4 forward filter rule 506 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 507 action 'jump'
set firewall ipv4 forward filter rule 507 description 'IOT to WAN policies'
set firewall ipv4 forward filter rule 507 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 507 jump-target 'IOT-WAN-v4'
set firewall ipv4 forward filter rule 507 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 510 action 'drop'
set firewall ipv4 forward filter rule 510 description 'ZONE IOT default-action'
set firewall ipv4 forward filter rule 510 outbound-interface interface-group 'ZONE_IOT'
# CCTV
set firewall ipv4 forward filter rule 601 action 'accept'
set firewall ipv4 forward filter rule 601 description 'CCTV intra-zone policies'
set firewall ipv4 forward filter rule 601 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 601 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 602 action 'jump'
set firewall ipv4 forward filter rule 602 description 'CCTV to MGMT policies'
set firewall ipv4 forward filter rule 602 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 602 jump-target 'CCTV-MGMT-v4'
set firewall ipv4 forward filter rule 602 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 603 action 'jump'
set firewall ipv4 forward filter rule 603 description 'CCTV to INFRA policies'
set firewall ipv4 forward filter rule 603 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 603 jump-target 'CCTV-INFRA-v4'
set firewall ipv4 forward filter rule 603 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 604 action 'jump'
set firewall ipv4 forward filter rule 604 description 'CCTV to HOME policies'
set firewall ipv4 forward filter rule 604 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 604 jump-target 'CCTV-HOME-v4'
set firewall ipv4 forward filter rule 604 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 605 action 'jump'
set firewall ipv4 forward filter rule 605 description 'CCTV to IOT policies'
set firewall ipv4 forward filter rule 605 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 605 jump-target 'CCTV-IOT-v4'
set firewall ipv4 forward filter rule 605 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 606 action 'jump'
set firewall ipv4 forward filter rule 606 description 'CCTV to CONTAINERS policies'
set firewall ipv4 forward filter rule 606 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 606 jump-target 'CCTV-CONTAINERS-v4'
set firewall ipv4 forward filter rule 606 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 607 action 'jump'
set firewall ipv4 forward filter rule 607 description 'CCTV to WAN policies'
set firewall ipv4 forward filter rule 607 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 607 jump-target 'CCTV-WAN-v4'
set firewall ipv4 forward filter rule 607 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 610 action 'drop'
set firewall ipv4 forward filter rule 610 description 'ZONE CCTV default-action'
set firewall ipv4 forward filter rule 610 outbound-interface interface-group 'ZONE_CCTV'
# CONTAINERS
set firewall ipv4 forward filter rule 701 action 'accept'
set firewall ipv4 forward filter rule 701 description 'CONTAINERS intra-zone policies'
set firewall ipv4 forward filter rule 701 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 701 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 702 action 'jump'
set firewall ipv4 forward filter rule 702 description 'CONTAINERS to MGMT policies'
set firewall ipv4 forward filter rule 702 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 702 jump-target 'CONTAINERS-MGMT-v4'
set firewall ipv4 forward filter rule 702 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 forward filter rule 703 action 'jump'
set firewall ipv4 forward filter rule 703 description 'CONTAINERS to INFRA policies'
set firewall ipv4 forward filter rule 703 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 703 jump-target 'CONTAINERS-INFRA-v4'
set firewall ipv4 forward filter rule 703 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 forward filter rule 704 action 'jump'
set firewall ipv4 forward filter rule 704 description 'CONTAINERS to HOME policies'
set firewall ipv4 forward filter rule 704 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 704 jump-target 'CONTAINERS-HOME-v4'
set firewall ipv4 forward filter rule 704 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 forward filter rule 705 action 'jump'
set firewall ipv4 forward filter rule 705 description 'CONTAINERS to IOT policies'
set firewall ipv4 forward filter rule 705 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 705 jump-target 'CONTAINERS-IOT-v4'
set firewall ipv4 forward filter rule 705 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 forward filter rule 706 action 'jump'
set firewall ipv4 forward filter rule 706 description 'CONTAINERS to CCTV policies'
set firewall ipv4 forward filter rule 706 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 706 jump-target 'CONTAINERS-CCTV-v4'
set firewall ipv4 forward filter rule 706 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 forward filter rule 707 action 'jump'
set firewall ipv4 forward filter rule 707 description 'CONTAINERS to WAN policies'
set firewall ipv4 forward filter rule 707 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 forward filter rule 707 jump-target 'CONTAINERS-WAN-v4'
set firewall ipv4 forward filter rule 707 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 forward filter rule 710 action 'drop'
set firewall ipv4 forward filter rule 710 description 'ZONE CONTAINERS default-action'
set firewall ipv4 forward filter rule 710 outbound-interface interface-group 'ZONE_CONTAINERS'

## Input filter
set firewall ipv4 input filter rule 101 action 'jump'
set firewall ipv4 input filter rule 101 description 'MGMT to VYOS Policies'
set firewall ipv4 input filter rule 101 inbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 input filter rule 101 jump-target 'MGMT-VYOS-v4'
set firewall ipv4 input filter rule 201 action 'jump'
set firewall ipv4 input filter rule 201 description 'INFRA to VYOS Policies'
set firewall ipv4 input filter rule 201 inbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 input filter rule 201 jump-target 'INFRA-VYOS-v4'
set firewall ipv4 input filter rule 301 action 'jump'
set firewall ipv4 input filter rule 301 description 'HOME to VYOS Policies'
set firewall ipv4 input filter rule 301 inbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 input filter rule 301 jump-target 'HOME-VYOS-v4'
set firewall ipv4 input filter rule 401 action 'jump'
set firewall ipv4 input filter rule 401 description 'IOT to VYOS Policies'
set firewall ipv4 input filter rule 401 inbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 input filter rule 401 jump-target 'IOT-VYOS-v4'
set firewall ipv4 input filter rule 501 action 'jump'
set firewall ipv4 input filter rule 501 description 'CCTV to VYOS Policies'
set firewall ipv4 input filter rule 501 inbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 input filter rule 501 jump-target 'CCTV-VYOS-v4'
set firewall ipv4 input filter rule 601 action 'jump'
set firewall ipv4 input filter rule 601 description 'CONTAINERS to VYOS Policies'
set firewall ipv4 input filter rule 601 inbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 input filter rule 601 jump-target 'CONTAINERS-VYOS-v4'
set firewall ipv4 input filter rule 701 action 'jump'
set firewall ipv4 input filter rule 701 description 'WAN to VYOS Policies'
set firewall ipv4 input filter rule 701 inbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 input filter rule 701 jump-target 'WAN-VYOS-v4'
set firewall ipv4 input filter rule 999 action 'drop'

## Output filter
set firewall ipv4 output filter rule 101 action 'jump'
set firewall ipv4 output filter rule 101 description 'VYOS to MGMT Policies'
set firewall ipv4 output filter rule 101 outbound-interface interface-group 'ZONE_MGMT'
set firewall ipv4 output filter rule 201 action 'jump'
set firewall ipv4 output filter rule 201 description 'VYOS to INFRA Policies'
set firewall ipv4 output filter rule 201 outbound-interface interface-group 'ZONE_INFRA'
set firewall ipv4 output filter rule 301 action 'jump'
set firewall ipv4 output filter rule 301 description 'VYOS to HOME Policies'
set firewall ipv4 output filter rule 301 outbound-interface interface-group 'ZONE_HOME'
set firewall ipv4 output filter rule 401 action 'jump'
set firewall ipv4 output filter rule 401 description 'VYOS to IOT Policies'
set firewall ipv4 output filter rule 401 outbound-interface interface-group 'ZONE_IOT'
set firewall ipv4 output filter rule 501 action 'jump'
set firewall ipv4 output filter rule 501 description 'VYOS to CCTV Policies'
set firewall ipv4 output filter rule 501 outbound-interface interface-group 'ZONE_CCTV'
set firewall ipv4 output filter rule 601 action 'jump'
set firewall ipv4 output filter rule 601 description 'VYOS to CONTAINERS Policies'
set firewall ipv4 output filter rule 601 outbound-interface interface-group 'ZONE_CONTAINERS'
set firewall ipv4 output filter rule 701 action 'jump'
set firewall ipv4 output filter rule 701 description 'VYOS to WAN Policies'
set firewall ipv4 output filter rule 701 outbound-interface interface-group 'ZONE_WAN'
set firewall ipv4 output filter rule 999 action 'drop'
